### ISSUE TITLE
App cannot read the Atlantean Artifices in vault

### ISSUE THREAD

**Issue by graceoflives** [Malgardian/TQCollector#8]

**Comment by Malgardian** [comment]
Works just fine for me, can you elaborate?

**Comment by graceoflives** [comment]
I have two of them (one from each characters), sitting in a vault:
![image](https://user-images.githubusercontent.com/20889772/60059756-00351980-9718-11e9-988e-8ef3df76b2ad.png)
Yet app cannot read them. the name is not bold:
![image](https://user-images.githubusercontent.com/20889772/60059843-5d30cf80-9718-11e9-8466-1aafec567a6a.png)
In the same vault I placed artifacts and some easter egg items, which are recognized correctly. Only the artifices aren't.

**Comment by Malgardian** [comment]
Curious, my legendary artifice is recognized. I'll try with a normal version.

**Comment by Malgardian** [comment]
Sorry, can't reproduce this issue, works just fine for me. Are you using 1.2.2 and TQVaultAE 3.1?

Some far out idea: When did you get those artifices? Directly after release of the expansion?

**Comment by graceoflives** [comment]
I got one of them a few days after Atlantis release. The other was in version 2.5, about 10 days ago

**Comment by graceoflives** [comment]
do you want the vault file? I can send you my vault with the Artifice.

**Comment by Malgardian** [comment]
Yes, that would be for the best if you could send me that. Maybe my idea is correct.

**Comment by graceoflives** [comment]
[artifice.zip](https://github.com/Malgardian/TQCollector/files/3337021/artifice.zip)
here you are

**Comment by Malgardian** [comment]
Yeah, it's like I suspected. The file path of the relic in the vault file uses "/" instead of "\" which would be typical for TQ internal dbr paths. Some dev probably used "/" initially during development and it only recently got patched in a game update. TQVaultAE also doesn't consider it an Atlantis item because of that if you compare it to a recently dropped artifice charm which does get a ATL tag.

Might be worth a try to put those two charms you have into the inventory of a character and start the game. That should hopefully update them and get them recognized in TQC if my assumption is correct. (Hexediting the vault file would be another way).

**Comment by Malgardian** [comment]
Forget that, updating it that way doesn't work as I just found out by testing. I attached your vault file again with the changes made manually.

[Artifica.zip](https://github.com/Malgardian/TQCollector/files/3338683/Artifica.zip)

**Comment by Malgardian** [comment]
I assume this fixed it for you? Feel free to reopen the issue if not :)

**Comment by DarthSomebody** [comment]
TQAE 2.9 + RAG + ATL on Steam
TQ Collector 1.2.2.1
Atlantean Artifices are not recognized. All other charms are recognized.

![Capture](https://user-images.githubusercontent.com/10331302/76153586-32cc4a00-60ce-11ea-88c0-9f922324e482.PNG)

![Capture](https://user-images.githubusercontent.com/10331302/76153562-c94c3b80-60cd-11ea-9db6-6f55bead8b7f.PNG)
